name: Build and deploy

on:
  push:
    paths:
      - '.github/workflows/*.yml'
      - '*.csv'
      - '*.xml'
      - '*.html'
      - '*.py'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || !startsWith(github.ref_name, 'dependabot/')
    steps:

      - name: Initialize
        uses: actions/checkout@v5

      - name: Install build dependencies
        run: sudo apt-get install -y python3-matplotlib

      - name: Build
        run: mkdir build && python build_slides.py build && rm -rf build/.git

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: ${{ github.ref_name }}
          path: build

  deploy:
    needs: build
    if: github.event_name == 'push' && !startsWith(github.ref_name, 'dependabot/')

    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:

      - name: Initialize
        uses: actions/checkout@v5
        with:
          ref: gh-pages

      - name: Download build artifact
        uses: actions/download-artifact@v5

      - name: Build deployment index
        run: python build_index.py

      - name: Deploy to GitHub Pages
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: deploys ${{ github.ref_name }}
