name: Build and deploy

on:
  push:
    paths:
      - '.github/workflows/*.yml'
      - '*.csv'
      - '*.xml'
      - '*.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Initialize
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: sudo apt-get install -y python3-matplotlib

      - name: Build
        run: mkdir -p build/${{ github.ref_name }} && python build_slides.py build/${{ github.ref_name }} && rm -rf build/${{ github.ref_name }}/.git

#      - name: Upload build artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ github.ref_name }}
#          path: build/*

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: ${{ github.ref_name }}
          path: build/${{ github.ref_name }}

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:

      - name: Download build artifact
        uses: actions/download-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: ${{ github.ref_name }}
