name: Build and deploy

on:
  push:
    paths:
      - '.github/workflows/*.yml'
      - '*.csv'
      - '*.xml'
      - '*.html'
      - '*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Initialize
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: sudo apt-get install -y python3-matplotlib

      - name: Build
        run: mkdir build && python build_slides.py build && rm -rf build/.git

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.ref_name }}
          path: build

  deploy:
    needs: build

    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:

      - name: Initialize
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download build artifact
        uses: actions/download-artifact@v3

      - name: Deploy to GitHub Pages
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: deploys ${{ github.ref_name }}
